apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec: 
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: "amqp://rabbitmq.default.svc.cluster.local:5672"
  - name: durable
    value: false
  - name: deletedWhenUnused
    value: false
  - name: autoAck
    value: false
  - name: reconnectWait
    value: 0
  - name: protocol
    value: amqp
  - name: concurrency
    value: parallel
  - name: username
    value: admin
  - name: password
    value: password
  - name: ttlInSeconds
    value: 60
  - name: clientName
    value: {podName}
  - name: heartBeat
    value: 10s

