apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-mshrm-studio
spec:
  dnsNames:
    - "api.mshrm.studio"
    - "*.api.mshrm.studio"
  issuerRef:
    name: letsencrypt-nginx-wcard
    kind: Issuer
  secretName: api-mshrm-studio-secret