apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f Mshrm.Studio/docker-compose.yml -o ./k8s/
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: dapr-placement
  name: dapr-placement
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dapr-placement
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f Mshrm.Studio/docker-compose.yml -o ./k8s/
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/mshrmstudio-default: "true"
        io.kompose.service: dapr-placement
    spec:
      containers:
        - args:
            - ./placement
            - -port
            - "50000"
            - -log-level
            - debug
        - image: daprio/dapr:1.9.4
          name: dapr-placement
      restartPolicy: Always
