apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f Mshrm.Studio/docker-compose.yml -o ./k8s/
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: dapr-placement
  name: dapr-placement
spec:
  ports:
    - name: "50000"
      protocol: TCP
      port: 50000
      targetPort: 50000
  externalIPs: 
    - 157.245.34.113
  selector:
    io.kompose.service: dapr-placement

