apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-api-ingress
  labels:
    io.kompose.service: app-api-ingress
  #annotations:
    #service.beta.kubernetes.io/do-loadbalancer-certificate-id: "1234-5678-9012-3456"
    #service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    #service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "80"
    #service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
    #service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/health"
    #service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "3"
    #service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "5"
    #service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "3"
    #service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "5"
spec:
  ingressClassName: nginx
  rules:
  - host: api.mshrm.studio
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: mshrm-studio-auth-api
            port:
              number: 8080
      - path: /aggregator
        pathType: Prefix
        backend:
          service:
            name: mshrm-studio-api
            port:
              number: 8080