apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-api-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  ingressClassName: app-ingress
  rules:
    - http:
        paths:
        - path: /auth
          pathType: Prefix
          backend:
            service:
              name: auth
              port:
                number: 30251
        - path: /aggregator
          pathType: Prefix
          backend:
            service:
              name: aggregator
              port:
                number: 30250