apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
    name: app-api-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: api.mshrm.studio
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: mshrm-studio-auth-api
            port:
              number: 8080
      - path: /aggregator
        pathType: Prefix
        backend:
          service:
            name: mshrm-studio-api
            port:
              number: 8080