apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f Mshrm.Studio/docker-compose.yml -o ./k8s/
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: mshrm-studio-api
  name: mshrm-studio-api
spec:
  type: NodePort 
  ports:
    - name: "30230"
      port: 8081
      targetPort: 8081
      nodePort: 30230
    - name: "30250"
      port: 8080
      targetPort: 8080
      nodePort: 30250
  externalIPs: 
    - 157.245.34.113
  selector:
    io.kompose.service: mshrm-studio-api
