apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f Mshrm.Studio/docker-compose.yml -o ./k8s/
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: mshrm-studio-api
  name: mshrm-studio-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mshrm-studio-api
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f Mshrm.Studio/docker-compose.yml -o ./k8s/
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/mshrmstudio-default: "true"
        io.kompose.service: mshrm-studio-api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          image: mshrmstudioapi
          livenessProbe:
            exec:
              command:
                - curl --fail http://localhost:80/health || exit 1
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 30
          name: mshrm-studio-api
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
      restartPolicy: Always
