kind: PersistentVolume
apiVersion: v1
metadata:
  name: dapr-config-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "Mshrm.Studio/DaprComponents"