apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 5672
    targetPort: 5672
    name: rabbitmq
  selector:
    app: rabbitmq