apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f Mshrm.Studio/docker-compose.yml -o ./k8s/
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: redis-cluster
  metadata:
  name: redis-cluster
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-cluster
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f Mshrm.Studio/docker-compose.yml -o ./k8s/
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/mshrmstudio-default: "true"
        io.kompose.service: redis-cluster
    spec:
      containers:
        - args:
            - redis-server
            - --save
            - "20"
            - "1"
            - --loglevel
            - warning
            - --requirepass
            - eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
          image: redis:alpine
          name: redis-cluster
          ports:
            - containerPort: 6379
              hostPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: cache
      restartPolicy: Always
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: cache
