// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mshrm.Studio.Localization.Api.Contexts;

#nullable disable

namespace Mshrm.Studio.Localization.Api.Migrations
{
    [DbContext(typeof(MshrmStudioLocalizationDbContext))]
    [Migration("20240318092024_AddedSeedData")]
    partial class AddedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mshrm.Studio.Localization.Api.Models.Entities.LocalizationResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GuidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocalizationArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalizationResources", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Culture = "en-US",
                            GuidId = new Guid("d568e126-2f53-4674-a3c5-b1255b4f9cf5"),
                            LocalizationArea = "Errors",
                            Name = "RoleDoesntExist",
                            Value = "Role doesn't exist"
                        },
                        new
                        {
                            Id = 2,
                            Culture = "en-US",
                            GuidId = new Guid("9ad6d8a8-2c0a-42bf-b580-cf25b8edd672"),
                            LocalizationArea = "Errors",
                            Name = "UserDoesntExist",
                            Value = "User doesn't exist"
                        },
                        new
                        {
                            Id = 3,
                            Culture = "en-US",
                            GuidId = new Guid("3a0614a8-3fc8-4ded-a33c-892082a44412"),
                            LocalizationArea = "Errors",
                            Name = "IpNotValid",
                            Value = "The IP address provided is not valid"
                        },
                        new
                        {
                            Id = 4,
                            Culture = "en-US",
                            GuidId = new Guid("085b1340-8629-427b-89c1-20321d3cd2bd"),
                            LocalizationArea = "Errors",
                            Name = "EmailNotFound",
                            Value = "Email doesn't exist"
                        },
                        new
                        {
                            Id = 5,
                            Culture = "en-US",
                            GuidId = new Guid("4319e9c9-ce8b-494d-b8c2-ade6889a530b"),
                            LocalizationArea = "Errors",
                            Name = "FailedToCreateIdentityUser",
                            Value = "Failed to create identity user"
                        },
                        new
                        {
                            Id = 6,
                            Culture = "en-US",
                            GuidId = new Guid("dcae985d-f716-4d69-a920-87823fed5e7e"),
                            LocalizationArea = "Errors",
                            Name = "FailedToCreateDomainUser",
                            Value = "Failed to create domain user"
                        },
                        new
                        {
                            Id = 7,
                            Culture = "en-US",
                            GuidId = new Guid("ac72cfd1-2fe2-4b59-8308-26171241b61a"),
                            LocalizationArea = "Errors",
                            Name = "CannotViewOtherUsersData",
                            Value = "Non admin users can only see their own data"
                        },
                        new
                        {
                            Id = 8,
                            Culture = "en-US",
                            GuidId = new Guid("5a16acf5-f794-427c-a128-8db32a254e83"),
                            LocalizationArea = "Errors",
                            Name = "EmailIsInvalid Email",
                            Value = "is invalid"
                        },
                        new
                        {
                            Id = 9,
                            Culture = "en-US",
                            GuidId = new Guid("0d360a82-e513-4e3b-a204-2792154119c8"),
                            LocalizationArea = "Errors",
                            Name = "FailedToGenerateToken",
                            Value = "Failed to generate token"
                        },
                        new
                        {
                            Id = 10,
                            Culture = "en-US",
                            GuidId = new Guid("1381faf1-54b9-48d4-b4a5-a843c236e3e1"),
                            LocalizationArea = "Errors",
                            Name = "UserLockedOut",
                            Value = "User is locked out"
                        },
                        new
                        {
                            Id = 11,
                            Culture = "en-US",
                            GuidId = new Guid("64846125-9116-47c2-a99c-644703e72b9d"),
                            LocalizationArea = "Errors",
                            Name = "UserRequiresConfirmation",
                            Value = "User requires confirmation"
                        },
                        new
                        {
                            Id = 12,
                            Culture = "en-US",
                            GuidId = new Guid("bfd59788-748c-4546-885b-8e2216baff42"),
                            LocalizationArea = "Errors",
                            Name = "FailedToRefreshToken",
                            Value = "Failed to refresh token"
                        },
                        new
                        {
                            Id = 13,
                            Culture = "en-US",
                            GuidId = new Guid("007e45ae-a92b-4250-a25d-94a1449aeaee"),
                            LocalizationArea = "Errors",
                            Name = "UserAlreadyExists",
                            Value = "User already exists"
                        },
                        new
                        {
                            Id = 14,
                            Culture = "en-US",
                            GuidId = new Guid("8cfed9e9-a7c0-4ca8-ba16-bc4d5cebeb11"),
                            LocalizationArea = "Errors",
                            Name = "FailedToGenerateConfirmationToken",
                            Value = "Failed to generate confirmation token"
                        },
                        new
                        {
                            Id = 15,
                            Culture = "en-US",
                            GuidId = new Guid("669c5215-3d5a-409f-b746-43d2174674fb"),
                            LocalizationArea = "Errors",
                            Name = "CannotViewOtherUsersData",
                            Value = "Non admin users can only see their own data"
                        },
                        new
                        {
                            Id = 16,
                            Culture = "en-US",
                            GuidId = new Guid("0c38d0bf-3bc6-424b-8c5d-fe61da7b97e1"),
                            LocalizationArea = "Errors",
                            Name = "FailedToGenerateResetToken",
                            Value = "Password could not be reset"
                        },
                        new
                        {
                            Id = 17,
                            Culture = "en-US",
                            GuidId = new Guid("2e9d10c4-9d59-48df-97a2-0e60881fb7ab"),
                            LocalizationArea = "Errors",
                            Name = "FailedToUpdatePassword",
                            Value = "Failed to update password"
                        },
                        new
                        {
                            Id = 18,
                            Culture = "en-US",
                            GuidId = new Guid("2578d493-804d-4174-846e-9ba72228a500"),
                            LocalizationArea = "Errors",
                            Name = "AlreadyConfirmed",
                            Value = "Already confirmed"
                        },
                        new
                        {
                            Id = 19,
                            Culture = "en-US",
                            GuidId = new Guid("17cb6b93-c9c8-4d3b-b51c-3d555442ea17"),
                            LocalizationArea = "Errors",
                            Name = "FailedToValidateConfirmationToken",
                            Value = "Failed to validate confirmation token"
                        },
                        new
                        {
                            Id = 20,
                            Culture = "en-US",
                            GuidId = new Guid("674ffbe9-9d39-4663-8ff7-fc0305373a26"),
                            LocalizationArea = "Errors",
                            Name = "ContactFormDoesntExist",
                            Value = "Contact form doesn't exist"
                        },
                        new
                        {
                            Id = 21,
                            Culture = "en-US",
                            GuidId = new Guid("1fa13ead-1cac-4f0c-ad13-08a259e61e86"),
                            LocalizationArea = "Errors",
                            Name = "ToolDoesntExist",
                            Value = "Tool doesn't exist"
                        },
                        new
                        {
                            Id = 22,
                            Culture = "en-US",
                            GuidId = new Guid("53117493-56d8-4188-a450-25297e14a25d"),
                            LocalizationArea = "Errors",
                            Name = "FailedToSendEmail",
                            Value = "Failed to send email"
                        },
                        new
                        {
                            Id = 23,
                            Culture = "en-US",
                            GuidId = new Guid("bf36753c-b8c6-4edf-b483-20e15e07ffe5"),
                            LocalizationArea = "Errors",
                            Name = "NoEmailTypeRegistered",
                            Value = "No email type has been registered for the email being sent"
                        },
                        new
                        {
                            Id = 24,
                            Culture = "en-US",
                            GuidId = new Guid("250b23f4-70a9-4232-b4fc-a80cbe3b1964"),
                            LocalizationArea = "Errors",
                            Name = "LocalizationResourceAlreadyExists",
                            Value = "Localization resource already exists"
                        },
                        new
                        {
                            Id = 25,
                            Culture = "en-US",
                            GuidId = new Guid("6aebdbc8-c2ae-45ea-9e02-66700945813f"),
                            LocalizationArea = "Errors",
                            Name = "LocalizationResourceDoesntExist",
                            Value = "Localization resource doesn't exist"
                        },
                        new
                        {
                            Id = 26,
                            Culture = "en-US",
                            GuidId = new Guid("0eadd8d6-9e1c-4a67-a863-fc712c31f25f"),
                            LocalizationArea = "Errors",
                            Name = "CurrencyAlreadyExists",
                            Value = "The currency already exists"
                        },
                        new
                        {
                            Id = 27,
                            Culture = "en-US",
                            GuidId = new Guid("ebe64cac-da3e-413a-822a-4dd51bcc5cc5"),
                            LocalizationArea = "Errors",
                            Name = "CurrencyNotSupported",
                            Value = "Currency is not supported by the provider"
                        },
                        new
                        {
                            Id = 28,
                            Culture = "en-US",
                            GuidId = new Guid("62b37378-0f95-41a9-8454-1bb0d87e18f5"),
                            LocalizationArea = "Errors",
                            Name = "BaseCurrencyNotSupported",
                            Value = "The base currency symbol provided is not supported"
                        },
                        new
                        {
                            Id = 29,
                            Culture = "en-US",
                            GuidId = new Guid("628085ae-5b9d-488d-bf09-48ac3a39cd05"),
                            LocalizationArea = "Errors",
                            Name = "BaseCurrencyPriceDoesntExist",
                            Value = "The base currency symbols price doesn't exist"
                        },
                        new
                        {
                            Id = 30,
                            Culture = "en-US",
                            GuidId = new Guid("ed07a053-7f56-41a8-a0a5-7870d593526a"),
                            LocalizationArea = "Errors",
                            Name = "CurrencyDoesntExist",
                            Value = "The currency doesn't exists"
                        },
                        new
                        {
                            Id = 31,
                            Culture = "en-US",
                            GuidId = new Guid("70e0d351-0a13-4819-81df-40854fd04201"),
                            LocalizationArea = "Errors",
                            Name = "TemporaryFileNotFound",
                            Value = "Temporary file not found"
                        },
                        new
                        {
                            Id = 32,
                            Culture = "en-US",
                            GuidId = new Guid("c99ad72a-2a1b-477a-ae08-38a5326fc424"),
                            LocalizationArea = "Errors",
                            Name = "KeyNotProvided",
                            Value = "Key must be provided"
                        },
                        new
                        {
                            Id = 33,
                            Culture = "en-US",
                            GuidId = new Guid("82d75ed9-5270-41a8-8b81-358a421f0c4c"),
                            LocalizationArea = "Errors",
                            Name = "FileNotFound",
                            Value = "File not found"
                        },
                        new
                        {
                            Id = 34,
                            Culture = "en-US",
                            GuidId = new Guid("39c7bb7c-d6c4-412b-863d-3fb743dcf8e8"),
                            LocalizationArea = "Errors",
                            Name = "ResourceDoesntExist",
                            Value = "Resource doesn't exist"
                        },
                        new
                        {
                            Id = 35,
                            Culture = "en-US",
                            GuidId = new Guid("78f1f443-a0a6-4f99-9948-099e2d24a4d4"),
                            LocalizationArea = "Errors",
                            Name = "ResourceIsPrivate",
                            Value = "Cannot view this resource unauthenticated"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
