// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mshrm.Studio.Localization.Api.Contexts;

#nullable disable

namespace Mshrm.Studio.Localization.Api.Migrations
{
    [DbContext(typeof(MshrmStudioLocalizationDbContext))]
    [Migration("20240612030805_UpdatedKey")]
    partial class UpdatedKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mshrm.Studio.Localization.Api.Models.Entities.LocalizationResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GuidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalizationArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalizationResources", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Culture = "en-US",
                            GuidId = new Guid("9883c99f-0000-0000-0000-000000000000"),
                            Key = "RoleDoesntExist",
                            LocalizationArea = "Errors",
                            Value = "Role doesn't exist"
                        },
                        new
                        {
                            Id = 2,
                            Culture = "en-US",
                            GuidId = new Guid("bfdbdce1-0000-0000-0000-000000000000"),
                            Key = "UserDoesntExist",
                            LocalizationArea = "Errors",
                            Value = "User doesn't exist"
                        },
                        new
                        {
                            Id = 3,
                            Culture = "en-US",
                            GuidId = new Guid("7aeda311-0000-0000-0000-000000000000"),
                            Key = "IpNotValid",
                            LocalizationArea = "Errors",
                            Value = "The IP address provided is not valid"
                        },
                        new
                        {
                            Id = 4,
                            Culture = "en-US",
                            GuidId = new Guid("dda39430-0000-0000-0000-000000000000"),
                            Key = "EmailNotFound",
                            LocalizationArea = "Errors",
                            Value = "Email doesn't exist"
                        },
                        new
                        {
                            Id = 5,
                            Culture = "en-US",
                            GuidId = new Guid("9b4f4d7c-0000-0000-0000-000000000000"),
                            Key = "FailedToCreateIdentityUser",
                            LocalizationArea = "Errors",
                            Value = "Failed to create identity user"
                        },
                        new
                        {
                            Id = 6,
                            Culture = "en-US",
                            GuidId = new Guid("e7dcf3da-0000-0000-0000-000000000000"),
                            Key = "FailedToCreateDomainUser",
                            LocalizationArea = "Errors",
                            Value = "Failed to create domain user"
                        },
                        new
                        {
                            Id = 7,
                            Culture = "en-US",
                            GuidId = new Guid("b2f64f03-0000-0000-0000-000000000000"),
                            Key = "CannotViewOtherUsersData",
                            LocalizationArea = "Errors",
                            Value = "Non admin users can only see their own data"
                        },
                        new
                        {
                            Id = 8,
                            Culture = "en-US",
                            GuidId = new Guid("fac2a8cd-0000-0000-0000-000000000000"),
                            Key = "EmailIsInvalid Email",
                            LocalizationArea = "Errors",
                            Value = "is invalid"
                        },
                        new
                        {
                            Id = 9,
                            Culture = "en-US",
                            GuidId = new Guid("7ec54fe2-0000-0000-0000-000000000000"),
                            Key = "FailedToGenerateToken",
                            LocalizationArea = "Errors",
                            Value = "Failed to generate token"
                        },
                        new
                        {
                            Id = 10,
                            Culture = "en-US",
                            GuidId = new Guid("d48e4db7-0000-0000-0000-000000000000"),
                            Key = "UserLockedOut",
                            LocalizationArea = "Errors",
                            Value = "User is locked out"
                        },
                        new
                        {
                            Id = 11,
                            Culture = "en-US",
                            GuidId = new Guid("b824dd67-0000-0000-0000-000000000000"),
                            Key = "UserRequiresConfirmation",
                            LocalizationArea = "Errors",
                            Value = "User requires confirmation"
                        },
                        new
                        {
                            Id = 12,
                            Culture = "en-US",
                            GuidId = new Guid("580488c5-0000-0000-0000-000000000000"),
                            Key = "FailedToRefreshToken",
                            LocalizationArea = "Errors",
                            Value = "Failed to refresh token"
                        },
                        new
                        {
                            Id = 13,
                            Culture = "en-US",
                            GuidId = new Guid("d9f10ea2-0000-0000-0000-000000000000"),
                            Key = "UserAlreadyExists",
                            LocalizationArea = "Errors",
                            Value = "User already exists"
                        },
                        new
                        {
                            Id = 14,
                            Culture = "en-US",
                            GuidId = new Guid("971ade7d-0000-0000-0000-000000000000"),
                            Key = "FailedToGenerateConfirmationToken",
                            LocalizationArea = "Errors",
                            Value = "Failed to generate confirmation token"
                        },
                        new
                        {
                            Id = 15,
                            Culture = "en-US",
                            GuidId = new Guid("b2f64f03-0000-0000-0000-000000000000"),
                            Key = "CannotViewOtherUsersData",
                            LocalizationArea = "Errors",
                            Value = "Non admin users can only see their own data"
                        },
                        new
                        {
                            Id = 16,
                            Culture = "en-US",
                            GuidId = new Guid("b07f69dd-0000-0000-0000-000000000000"),
                            Key = "FailedToGenerateResetToken",
                            LocalizationArea = "Errors",
                            Value = "Password could not be reset"
                        },
                        new
                        {
                            Id = 17,
                            Culture = "en-US",
                            GuidId = new Guid("87ed5b61-0000-0000-0000-000000000000"),
                            Key = "FailedToUpdatePassword",
                            LocalizationArea = "Errors",
                            Value = "Failed to update password"
                        },
                        new
                        {
                            Id = 18,
                            Culture = "en-US",
                            GuidId = new Guid("8b7d01af-0000-0000-0000-000000000000"),
                            Key = "AlreadyConfirmed",
                            LocalizationArea = "Errors",
                            Value = "Already confirmed"
                        },
                        new
                        {
                            Id = 19,
                            Culture = "en-US",
                            GuidId = new Guid("83e56390-0000-0000-0000-000000000000"),
                            Key = "FailedToValidateConfirmationToken",
                            LocalizationArea = "Errors",
                            Value = "Failed to validate confirmation token"
                        },
                        new
                        {
                            Id = 20,
                            Culture = "en-US",
                            GuidId = new Guid("61294040-0000-0000-0000-000000000000"),
                            Key = "ContactFormDoesntExist",
                            LocalizationArea = "Errors",
                            Value = "Contact form doesn't exist"
                        },
                        new
                        {
                            Id = 21,
                            Culture = "en-US",
                            GuidId = new Guid("0329fb3a-0000-0000-0000-000000000000"),
                            Key = "ToolDoesntExist",
                            LocalizationArea = "Errors",
                            Value = "Tool doesn't exist"
                        },
                        new
                        {
                            Id = 22,
                            Culture = "en-US",
                            GuidId = new Guid("5a9998e0-0000-0000-0000-000000000000"),
                            Key = "FailedToSendEmail",
                            LocalizationArea = "Errors",
                            Value = "Failed to send email"
                        },
                        new
                        {
                            Id = 23,
                            Culture = "en-US",
                            GuidId = new Guid("28aeb50d-0000-0000-0000-000000000000"),
                            Key = "NoEmailTypeRegistered",
                            LocalizationArea = "Errors",
                            Value = "No email type has been registered for the email being sent"
                        },
                        new
                        {
                            Id = 24,
                            Culture = "en-US",
                            GuidId = new Guid("3ef433fa-0000-0000-0000-000000000000"),
                            Key = "LocalizationResourceAlreadyExists",
                            LocalizationArea = "Errors",
                            Value = "Localization resource already exists"
                        },
                        new
                        {
                            Id = 25,
                            Culture = "en-US",
                            GuidId = new Guid("60582306-0000-0000-0000-000000000000"),
                            Key = "LocalizationResourceDoesntExist",
                            LocalizationArea = "Errors",
                            Value = "Localization resource doesn't exist"
                        },
                        new
                        {
                            Id = 26,
                            Culture = "en-US",
                            GuidId = new Guid("455d0715-0000-0000-0000-000000000000"),
                            Key = "AssetAlreadyExists",
                            LocalizationArea = "Errors",
                            Value = "The asset already exists"
                        },
                        new
                        {
                            Id = 27,
                            Culture = "en-US",
                            GuidId = new Guid("20d5260b-0000-0000-0000-000000000000"),
                            Key = "AssetNotSupported",
                            LocalizationArea = "Errors",
                            Value = "Asset is not supported by the provider"
                        },
                        new
                        {
                            Id = 28,
                            Culture = "en-US",
                            GuidId = new Guid("c9f197da-0000-0000-0000-000000000000"),
                            Key = "BaseAssetNotSupported",
                            LocalizationArea = "Errors",
                            Value = "The base asset symbol provided is not supported"
                        },
                        new
                        {
                            Id = 29,
                            Culture = "en-US",
                            GuidId = new Guid("8dac8ede-0000-0000-0000-000000000000"),
                            Key = "BaseAssetPriceDoesntExist",
                            LocalizationArea = "Errors",
                            Value = "The base asset symbols price doesn't exist"
                        },
                        new
                        {
                            Id = 30,
                            Culture = "en-US",
                            GuidId = new Guid("c0df2371-0000-0000-0000-000000000000"),
                            Key = "AssetDoesntExist",
                            LocalizationArea = "Errors",
                            Value = "The asset doesn't exists"
                        },
                        new
                        {
                            Id = 31,
                            Culture = "en-US",
                            GuidId = new Guid("1de54c93-0000-0000-0000-000000000000"),
                            Key = "TemporaryFileNotFound",
                            LocalizationArea = "Errors",
                            Value = "Temporary file not found"
                        },
                        new
                        {
                            Id = 32,
                            Culture = "en-US",
                            GuidId = new Guid("1ef82270-0000-0000-0000-000000000000"),
                            Key = "KeyNotProvided",
                            LocalizationArea = "Errors",
                            Value = "Key must be provided"
                        },
                        new
                        {
                            Id = 33,
                            Culture = "en-US",
                            GuidId = new Guid("01e3a1f4-0000-0000-0000-000000000000"),
                            Key = "FileNotFound",
                            LocalizationArea = "Errors",
                            Value = "File not found"
                        },
                        new
                        {
                            Id = 34,
                            Culture = "en-US",
                            GuidId = new Guid("c1585671-0000-0000-0000-000000000000"),
                            Key = "ResourceDoesntExist",
                            LocalizationArea = "Errors",
                            Value = "Resource doesn't exist"
                        },
                        new
                        {
                            Id = 35,
                            Culture = "en-US",
                            GuidId = new Guid("7cd16eab-0000-0000-0000-000000000000"),
                            Key = "ResourceIsPrivate",
                            LocalizationArea = "Errors",
                            Value = "Cannot view this resource unauthenticated"
                        },
                        new
                        {
                            Id = 36,
                            Culture = "en-US",
                            GuidId = new Guid("e7f39836-0000-0000-0000-000000000000"),
                            Key = "SystemError",
                            LocalizationArea = "Errors",
                            Value = "System error, please contact admin"
                        },
                        new
                        {
                            Id = 37,
                            Culture = "en-US",
                            GuidId = new Guid("4832254a-0000-0000-0000-000000000000"),
                            Key = "PricingStructureDoesntExist",
                            LocalizationArea = "Errors",
                            Value = "The pricing structure doesn't exist"
                        },
                        new
                        {
                            Id = 38,
                            Culture = "en-US",
                            GuidId = new Guid("55a58ae7-0000-0000-0000-000000000000"),
                            Key = "AssetPriceMustBeACurrency",
                            LocalizationArea = "Errors",
                            Value = "The asset price must be a currency"
                        },
                        new
                        {
                            Id = 39,
                            Culture = "en-US",
                            GuidId = new Guid("d3e735e8-0000-0000-0000-000000000000"),
                            Key = "FailureCodeIsInvalid",
                            LocalizationArea = "Errors",
                            Value = "The failure code provided is invalid"
                        },
                        new
                        {
                            Id = 40,
                            Culture = "en-US",
                            GuidId = new Guid("f8f578b3-0000-0000-0000-000000000000"),
                            Key = "LocalizationAreaNotSupported",
                            LocalizationArea = "Errors",
                            Value = "The localization area provided is not supported"
                        },
                        new
                        {
                            Id = 41,
                            Culture = "en-US",
                            GuidId = new Guid("42629b7a-0000-0000-0000-000000000000"),
                            Key = "CultureNotSupported",
                            LocalizationArea = "Errors",
                            Value = "The culture provided is not supported"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
