// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mshrm.Studio.Localization.Api.Contexts;

#nullable disable

namespace Mshrm.Studio.Localization.Api.Migrations
{
    [DbContext(typeof(MshrmStudioLocalizationDbContext))]
    partial class MshrmStudioLocalizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mshrm.Studio.Localization.Api.Models.Entities.LocalizationResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GuidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocalizationArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalizationResources", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Culture = "en-US",
                            GuidId = new Guid("c412242e-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "RoleDoesntExist",
                            Value = "Role doesn't exist"
                        },
                        new
                        {
                            Id = 2,
                            Culture = "en-US",
                            GuidId = new Guid("40da5f8d-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "UserDoesntExist",
                            Value = "User doesn't exist"
                        },
                        new
                        {
                            Id = 3,
                            Culture = "en-US",
                            GuidId = new Guid("02aa7313-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "IpNotValid",
                            Value = "The IP address provided is not valid"
                        },
                        new
                        {
                            Id = 4,
                            Culture = "en-US",
                            GuidId = new Guid("3b741795-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "EmailNotFound",
                            Value = "Email doesn't exist"
                        },
                        new
                        {
                            Id = 5,
                            Culture = "en-US",
                            GuidId = new Guid("c986530e-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "FailedToCreateIdentityUser",
                            Value = "Failed to create identity user"
                        },
                        new
                        {
                            Id = 6,
                            Culture = "en-US",
                            GuidId = new Guid("2038106f-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "FailedToCreateDomainUser",
                            Value = "Failed to create domain user"
                        },
                        new
                        {
                            Id = 7,
                            Culture = "en-US",
                            GuidId = new Guid("3cfae5a2-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "CannotViewOtherUsersData",
                            Value = "Non admin users can only see their own data"
                        },
                        new
                        {
                            Id = 8,
                            Culture = "en-US",
                            GuidId = new Guid("e92f9f37-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "EmailIsInvalid Email",
                            Value = "is invalid"
                        },
                        new
                        {
                            Id = 9,
                            Culture = "en-US",
                            GuidId = new Guid("7df6faf7-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "FailedToGenerateToken",
                            Value = "Failed to generate token"
                        },
                        new
                        {
                            Id = 10,
                            Culture = "en-US",
                            GuidId = new Guid("02f47445-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "UserLockedOut",
                            Value = "User is locked out"
                        },
                        new
                        {
                            Id = 11,
                            Culture = "en-US",
                            GuidId = new Guid("36421318-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "UserRequiresConfirmation",
                            Value = "User requires confirmation"
                        },
                        new
                        {
                            Id = 12,
                            Culture = "en-US",
                            GuidId = new Guid("46c4cdef-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "FailedToRefreshToken",
                            Value = "Failed to refresh token"
                        },
                        new
                        {
                            Id = 13,
                            Culture = "en-US",
                            GuidId = new Guid("56e73ab4-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "UserAlreadyExists",
                            Value = "User already exists"
                        },
                        new
                        {
                            Id = 14,
                            Culture = "en-US",
                            GuidId = new Guid("4d04932b-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "FailedToGenerateConfirmationToken",
                            Value = "Failed to generate confirmation token"
                        },
                        new
                        {
                            Id = 15,
                            Culture = "en-US",
                            GuidId = new Guid("3cfae5a2-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "CannotViewOtherUsersData",
                            Value = "Non admin users can only see their own data"
                        },
                        new
                        {
                            Id = 16,
                            Culture = "en-US",
                            GuidId = new Guid("859d1c16-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "FailedToGenerateResetToken",
                            Value = "Password could not be reset"
                        },
                        new
                        {
                            Id = 17,
                            Culture = "en-US",
                            GuidId = new Guid("4965bd5b-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "FailedToUpdatePassword",
                            Value = "Failed to update password"
                        },
                        new
                        {
                            Id = 18,
                            Culture = "en-US",
                            GuidId = new Guid("49e7c86e-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "AlreadyConfirmed",
                            Value = "Already confirmed"
                        },
                        new
                        {
                            Id = 19,
                            Culture = "en-US",
                            GuidId = new Guid("50c36127-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "FailedToValidateConfirmationToken",
                            Value = "Failed to validate confirmation token"
                        },
                        new
                        {
                            Id = 20,
                            Culture = "en-US",
                            GuidId = new Guid("7e0da04d-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "ContactFormDoesntExist",
                            Value = "Contact form doesn't exist"
                        },
                        new
                        {
                            Id = 21,
                            Culture = "en-US",
                            GuidId = new Guid("e06b6f0a-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "ToolDoesntExist",
                            Value = "Tool doesn't exist"
                        },
                        new
                        {
                            Id = 22,
                            Culture = "en-US",
                            GuidId = new Guid("b155ce82-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "FailedToSendEmail",
                            Value = "Failed to send email"
                        },
                        new
                        {
                            Id = 23,
                            Culture = "en-US",
                            GuidId = new Guid("590a0955-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "NoEmailTypeRegistered",
                            Value = "No email type has been registered for the email being sent"
                        },
                        new
                        {
                            Id = 24,
                            Culture = "en-US",
                            GuidId = new Guid("c8b746ef-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "LocalizationResourceAlreadyExists",
                            Value = "Localization resource already exists"
                        },
                        new
                        {
                            Id = 25,
                            Culture = "en-US",
                            GuidId = new Guid("944d91ec-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "LocalizationResourceDoesntExist",
                            Value = "Localization resource doesn't exist"
                        },
                        new
                        {
                            Id = 26,
                            Culture = "en-US",
                            GuidId = new Guid("38ac0623-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "CurrencyAlreadyExists",
                            Value = "The currency already exists"
                        },
                        new
                        {
                            Id = 27,
                            Culture = "en-US",
                            GuidId = new Guid("af58d46e-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "CurrencyNotSupported",
                            Value = "Currency is not supported by the provider"
                        },
                        new
                        {
                            Id = 28,
                            Culture = "en-US",
                            GuidId = new Guid("13236e27-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "BaseCurrencyNotSupported",
                            Value = "The base currency symbol provided is not supported"
                        },
                        new
                        {
                            Id = 29,
                            Culture = "en-US",
                            GuidId = new Guid("7c3e4555-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "BaseCurrencyPriceDoesntExist",
                            Value = "The base currency symbols price doesn't exist"
                        },
                        new
                        {
                            Id = 30,
                            Culture = "en-US",
                            GuidId = new Guid("f63dd92b-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "CurrencyDoesntExist",
                            Value = "The currency doesn't exists"
                        },
                        new
                        {
                            Id = 31,
                            Culture = "en-US",
                            GuidId = new Guid("002ed62b-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "TemporaryFileNotFound",
                            Value = "Temporary file not found"
                        },
                        new
                        {
                            Id = 32,
                            Culture = "en-US",
                            GuidId = new Guid("9331af71-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "KeyNotProvided",
                            Value = "Key must be provided"
                        },
                        new
                        {
                            Id = 33,
                            Culture = "en-US",
                            GuidId = new Guid("558a5b17-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "FileNotFound",
                            Value = "File not found"
                        },
                        new
                        {
                            Id = 34,
                            Culture = "en-US",
                            GuidId = new Guid("59e42c4f-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "ResourceDoesntExist",
                            Value = "Resource doesn't exist"
                        },
                        new
                        {
                            Id = 35,
                            Culture = "en-US",
                            GuidId = new Guid("15344791-0000-0000-0000-000000000000"),
                            LocalizationArea = "Errors",
                            Name = "ResourceIsPrivate",
                            Value = "Cannot view this resource unauthenticated"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
