// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mshrm.Studio.Subscription.Infrastructure.Contexts;

#nullable disable

namespace Mshrm.Studio.Subscription.Infrastructure.Migrations
{
    [DbContext(typeof(MshrmStudioSubscriptionDbContext))]
    [Migration("20240402110757_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mshrm.Studio.Subscription.Domain.PricingStructures.PricingStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GuidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("SubcriptionModelId")
                        .HasColumnType("int");

                    b.Property<string>("SupportedCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubcriptionModelId");

                    b.ToTable("PricingStructures", "dbo");
                });

            modelBuilder.Entity("Mshrm.Studio.Subscription.Domain.Subscriptions.SubscriptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GuidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LogoGuidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubscriptionModelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionModels", "dbo");
                });

            modelBuilder.Entity("Mshrm.Studio.Subscription.Domain.PricingStructures.PricingStructure", b =>
                {
                    b.HasOne("Mshrm.Studio.Subscription.Domain.Subscriptions.SubscriptionModel", "SubcriptionModel")
                        .WithMany("PricingStructures")
                        .HasForeignKey("SubcriptionModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Mshrm.Studio.Subscription.Domain.PricingStructures.ValueObjects.Discount", "Discount", b1 =>
                        {
                            b1.Property<int>("PricingStructureId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DiscountAmount");

                            b1.Property<decimal>("Percent")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DiscountPercent");

                            b1.Property<string>("Reason")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DiscountReason");

                            b1.HasKey("PricingStructureId");

                            b1.ToTable("PricingStructures", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("PricingStructureId");
                        });

                    b.Navigation("Discount")
                        .IsRequired();

                    b.Navigation("SubcriptionModel");
                });

            modelBuilder.Entity("Mshrm.Studio.Subscription.Domain.Subscriptions.SubscriptionModel", b =>
                {
                    b.Navigation("PricingStructures");
                });
#pragma warning restore 612, 618
        }
    }
}
